## Notebook 7 – Sampling

### 1. Sampling

Sampling is the process of selecting a smaller group of people, objects, or data points from a larger group in order to study the smaller group and learn something about the larger group.

OR

Sampling is the process of selecting a subset of individuals or items from a larger group (called the population) in order to study that subset and draw conclusions about the whole population.

The larger group is called the **population**, and the smaller group we select is called the **sample.**

**example**

Suppose a company has 100,000 customers.

You want to know:

"How satisfied are our customers with our service?"

It would be difficult and expensive to ask all 100,000 customers.

Instead, we might select 1,000 customers and ask them.

Here:

100,000 customers → Population
1,000 selected customers → Sample
Selecting those 1,000 customers → Sampling

**Sampling in AI/ML**

Sampling is extremely important in machine learning.

Imagine you have a dataset containing:

10 million customer records

You may want to:

Explore the data

Train a model

Test an idea

Perform statistical analysis


Working with all 10 million records may require significant memory and computation.

You might take a representative sample:

10,000,000 records
    
       ↓
    
    Sampling
    
       ↓
    
   100,000 records

You can then perform exploratory analysis on those 100,000 records.

Sampling is also used when creating:

Training datasets
    
Validation datasets
    
Test datasets
    
Survey datasets
    
Experimental datasets

In [1]:
import numpy as np

population = np.arange(1, 101)

sample = np.random.choice(population, size=10, replace=False)

print("Population:")
print(population)

print("\nSample:")
print(sample)

Population:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Sample:
[63  8 25 53 84 94 38 97 16  3]


### 2. Random Sampling

Random sampling is a sampling method in which every member of the population has an equal or known chance of being selected.

In simple random sampling, every member has an equal chance, and selections are made randomly.

**We don't intentionally choose specific member.**

**Why Random Sampling?**

Random sampling helps reduce selection bias.

In [2]:
import numpy as np

population = np.arange(1, 101)

sample = np.random.choice(
    population,
    size=10,
    replace=False
)

print("Random Sample:")
print(sample)

Random Sample:
[91 35 32 71 28 65 53 86 20 58]


**AI/ML Use Case**

Suppose you have:

1,000,000 customer records

and want to quickly explore the dataset.

You could randomly select:

50,000 customers

and perform:

Exploratory Data Analysis

Distribution analysis

Feature analysis

Initial model experiments

Random sampling can give a reasonably representative subset when the population is relatively homogeneous and there are no important subgroups being missed.

### 3. Stratified Sampling
Stratified sampling is a probability sampling method in which the population is first divided into non-overlapping, homogeneous subgroups called strata, and then a random sample is drawn independently from each stratum.

This is especially useful when the population contains different groups that are important to represent.

**Strata:** Subgroups formed on the basis of a shared characteristic (e.g., gender, age group, income level, region).

- Strata must be:

**Mutually exclusive:** each population member belongs to only one stratum.

**Collectively exhaustive:** every member belongs to some stratum.

Within each stratum, a probability method (often simple random sampling) is used to select units.

**For example, suppose a company has:**

10,000 employees

They are divided into:

Engineering
Sales
Marketing
HR
Finance

These groups can be called strata.

**AI/ML Use Case**

Imagine a classification dataset:

Cat → 5,000 images

Dog → 3,000 images

Horse → 2,000 images

If you randomly sample the dataset, you may not preserve the class proportions.

Stratified sampling can help ensure that the sample contains representatives from:

Cat

Dog

Horse

This idea is also closely related to stratified train/test splitting in machine learning.

For example, in classification, we often want the training and testing sets to preserve approximately the same class distribution.

In [3]:
import pandas as pd

data = pd.DataFrame({
    "Department": (
        ["Engineering"] * 50 +
        ["Sales"] * 20 +
        ["Marketing"] * 15 +
        ["HR"] * 10 +
        ["Finance"] * 5
    ),
    "Employee_ID": range(1, 101)
})

sample = data.groupby(
    "Department",
    group_keys=False
).apply(
    lambda group: group.sample(frac=0.20, random_state=42)
)

print(sample)

    Employee_ID
13           14
39           40
30           31
45           46
17           18
48           49
26           27
25           26
32           33
19           20
96           97
93           94
86           87
79           80
81           82
70           71
50           51
67           68
65           66
51           52


### 4. Cluster Sampling

Cluster sampling is a probability sampling method in which the population is divided into naturally occurring groups called clusters, a random sample of clusters is selected, and then individuals are sampled from those selected clusters.


*Stratified sampling*

We take samples from every group.

*Cluster sampling*

We select some groups, and study members within those selected groups.

**Why Cluster Sampling?**

Cluster sampling is useful when the population is geographically spread out.

For example:

Surveying students across India.

It would be expensive to randomly select students from every school in every state.

**AI/ML Use Case**

Suppose a company has customer data from:

100 cities

and wants to conduct an initial customer behavior analysis.

Instead of collecting data from every city, it could randomly select several cities and analyze customers from those cities.

This can be useful when data collection is expensive or geographically distributed.

In [4]:
import numpy as np

schools = {
    "School_A": list(range(1, 11)),
    "School_B": list(range(11, 21)),
    "School_C": list(range(21, 31)),
    "School_D": list(range(31, 41))
}

selected_schools = np.random.choice(
    list(schools.keys()),
    size=2,
    replace=False
)

print("Selected Schools:")
print(selected_schools)

sample = []

for school in selected_schools:
    sample.extend(schools[school])

print("\nStudents Selected:")
print(sample)

Selected Schools:
['School_B' 'School_D']

Students Selected:
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


### 5. Systematic Sampling

Systematic sampling is a probability sampling method in which elements are selected from an ordered list at regular intervals after a random starting point.

OR

Systematic sampling is a sampling method where we select members from a population at a regular interval after choosing a starting point.

Choose a starting point → then select every k-th member.

**Example**

Suppose we have:

Population = 1, 2, 3, ..., 100

We want:

10 samples

The sampling interval is:

$$ k=\frac{N}{n} $$

Where:

\(N\) = population size
\(n\) = sample size
\(k\) = sampling interval

Here:

$$ k=\frac{100}{10}=10 $$

Suppose our random starting point is:

4

Then we select:

4
14
24
34
44
54
64
74
84
94

That's systematic sampling.

**AI/ML Use Case**

Suppose a company receives:

1,000,000 transactions

and wants to inspect a smaller subset.

Instead of randomly generating every selected index, systematic sampling could select every:

100th transaction

after a random starting point.

**Important Warning**

Systematic sampling can be problematic if the data contains a periodic pattern.

For example, suppose every 10th record represents a particular type of customer.

If we select every 10th record, our sample could become heavily biased.

So systematic sampling works best when the ordering of the population does not introduce problematic patterns.

In [5]:
import numpy as np

population = np.arange(1, 101)

sample_size = 10

k = len(population) // sample_size

start = np.random.randint(0, k)

sample = population[start::k]

print("Sampling interval:", k)
print("Sample:")
print(sample)

Sampling interval: 10
Sample:
[ 9 19 29 39 49 59 69 79 89 99]


### 6. Sampling Bias

Sampling bias is a systematic error that occurs when some members of the population are **more (or less) likely to be included in the sample** than others, so the sample does not accurately represent the population.

OR

Sampling bias occurs when the method used to select a sample causes the sample to systematically differ from the population it is supposed to represent.

**Example**

Population:

10,000 students

Actual population:

60% Undergraduate
40% Postgraduate

But your sample contains:

95% Undergraduate
5% Postgraduate

Your sample doesn't properly represent the population.

Your results may therefore be misleading.

**Common Types of Sampling Bias**

- 1. Convenience Bias

   Selecting people who are easiest to reach.

Example:

Surveying only your friends.

- 2. Voluntary Response Bias

   People choose whether to participate.

Example:

An online survey where only people who strongly like/dislike something respond.

People with extreme opinions may be more likely to participate.

- 3. Undercoverage Bias

   Some groups are not sufficiently represented.

Example:

Conducting an online survey that excludes people without internet access.

- 4. Selection Bias

  The selection process systematically favors certain individuals.

Example:

Selecting only experienced employees for a company survey.

**Why Sampling Bias Matters in AI/ML**

Sampling bias can create biased datasets.

For example, imagine a face recognition dataset containing:

90% images from one demographic
10% images from other demographics

A model trained on this data may perform very differently across groups.

In [8]:
import pandas as pd

students = pd.DataFrame({
    "Student": range(1, 11),
    "Group": ["Library users"] * 4 + ["Non-users"] * 6,
    "Satisfied": [1, 1, 1, 0, 0, 0, 0, 1, 0, 0]
})

# Population satisfaction rate
population_rate = students["Satisfied"].mean()

# Biased sample: only library users
biased_sample = students[students["Group"] == "Library users"]
biased_rate = biased_sample["Satisfied"].mean()

print("Population satisfaction rate:", population_rate)
print("Satisfaction rate among library users:", biased_rate)

Population satisfaction rate: 0.4
Satisfaction rate among library users: 0.75


### 7. Sampling Error

Sampling error is the difference between a sample statistic (computed from the sample) and the true population parameter it is intended to estimate. It arises purely because we observe a sample instead of the entire population.

**Population parameter:** A numerical characteristic of the whole population (e.g., population mean μ, population proportion p).

**Sample statistic:** The corresponding value computed from the sample (e.g., sample mean xˉ ,sample proportion P^ )

$Sampling error = Sample statistic − Population parameter$

$Sampling Error=xˉ−μ$

**Let's understand with an example.**

Suppose the true population mean is:

$$ \mu=50 $$

You randomly select a sample.

Your sample mean is:

$$ \bar{x}=48 $$

Then the sampling error is:

$$ \bar{x}-\mu $$ $$ =48-50 $$ $$ =-2 $$

The sample mean is 2 units below the population mean.

In [11]:
import numpy as np

population = np.arange(1, 101)

population_mean = np.mean(population)

sample = np.random.choice(
    population,
    size=10,
    replace=False
)

sample_mean = np.mean(sample)

sampling_error = sample_mean - population_mean

print("Population Mean:", population_mean)
print("Sample Mean:", sample_mean)
print("Sampling Error:", sampling_error)

Population Mean: 50.5
Sample Mean: 56.1
Sampling Error: 5.600000000000001


### 8. Sample Size

Sample size is the number of observations (individuals, units, or measurements) included in a statistical sample. It is a key feature of any study that uses sampling to make inferences about a population

OR

Sample size is the number of observations or individuals included in a sample.

Sample size matters because it affects the precision of estimates, the ability to detect differences, the cost of data collection, and the reliability of statistical conclusions.



**Why Does Sample Size Matter?**

Consider two studies.

Study A

Population = 100,000

Sample = 10

Study B

Population = 100,000

Sample = 10,000

Study B generally has more information about the population.

In [14]:
import math

Z = 1.96
p = 0.5
E = 0.05

n = (Z**2 * p * (1 - p)) / (E**2)

print("Required sample size:", math.ceil(n))

Required sample size: 385


In [15]:
# Approximate sample size for estimating a population proportion

z = 1.96       # Approximately 95% confidence
p = 0.5        # Conservative assumption when proportion is unknown
E = 0.05       # 5 percentage-point margin of error

n0 = (z**2 * p * (1 - p)) / (E**2)

# Round up because sample size must be a whole number
sample_size = int(n0) + (1 if n0 % 1 else 0)

print("Calculated sample size:", n0)
print("Required whole-number sample size:", sample_size)

Calculated sample size: 384.1599999999999
Required whole-number sample size: 385
